#include <lcom/lcf.h>
#include "../src/sprites/ABC/A.xpm"
#include "../src/sprites/ABC/B.xpm"
#include "../src/sprites/ABC/C.xpm"
#include "../src/sprites/ABC/D.xpm"
#include "../src/sprites/ABC/E.xpm"
#include "../src/sprites/ABC/F.xpm"
#include "../src/sprites/ABC/G.xpm"
#include "../src/sprites/ABC/H.xpm"
#include "../src/sprites/ABC/I.xpm"
#include "../src/sprites/ABC/J.xpm"
#include "../src/sprites/ABC/K.xpm"
#include "../src/sprites/ABC/L.xpm"
#include "../src/sprites/ABC/M.xpm"
#include "../src/sprites/ABC/N.xpm"
#include "../src/sprites/ABC/O.xpm"
#include "../src/sprites/ABC/P.xpm"
#include "../src/sprites/ABC/Q.xpm"
#include "../src/sprites/ABC/R.xpm"
#include "../src/sprites/ABC/S.xpm"
#include "../src/sprites/ABC/T.xpm"
#include "../src/sprites/ABC/U.xpm"
#include "../src/sprites/ABC/V.xpm"
#include "../src/sprites/ABC/W.xpm"
#include "../src/sprites/ABC/X.xpm"
#include "../src/sprites/ABC/Y.xpm"
#include "../src/sprites/ABC/Z.xpm"




